### ISSUE TITLE
Not possible to install the library

### ISSUE THREAD

**Issue by mikekgr** [stelgenhof/NTPClient#2]
Dear Sir,
I have Arduino IDE 1.6.9 installed at Windows 10 laptop, and I tried to install your library both with the manual way ( download,, extract / rename the unzipped directory as NTPClient and transferred to the appropriate library directory ) and the Arduino "Add .ZIP library ..." way, both without success unfortunately... In the "Add .ZIP library ..."  I got the following error:  "Specified folder/zip file does not contain a valid library"

and in the manual way invalid library as well.

Please guide me what is wrong...

Thanks and Best Regards,
Mike Kranidis

P.S. Sorry, I forgot to say a BIG THANKS for your fine as I can understand library (sorry not possible to run it yet...!)

**Comment by stelgenhof** [comment]
@mikekgr Thank you for trying out the NTPClient library. My apologies for this as nothing is wrong with what you are doing. 

To be able to add a library to Arduino IDE,  library meta information in the form of a file called 'library.properties' needs to be present. Unfortunately I haven't included one, since I personally make little use of the Arduino IDE (Using PlatformIO). 

Let me include such a file as soon as possible so you can start using the library!

Cheers! Sacha

**Comment by mikekgr** [comment]
Dear Sacha,

thanks a lot!. When it is done please drop me a note.

Thanks and Best Regards,
Mike Kranidis

**Comment by stelgenhof** [comment]
@mikekgr The library.properties file has been added now. I tried myself in the Arduino IDE and could successfully compile and upload the example. Give it a try! (Please note this library has been designed _only_ for the ESP8266)

**Comment by mikekgr** [comment]
Thanks a lot Sir. I will try it later on and yes, I have ESP8266. 
Best Regards, 
Mike Kranidis
